import 'package:firebase_core/firebase_core.dart';

// This file would typically be generated by Firebase CLI
// For now, we're creating a placeholder for development

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyDkW5pIQvndgFQZHHcc2vAkxocPMm48o9o',
      appId: '1:560124260957:android:401ebb7c4d85cfd45e93b4',
      messagingSenderId: '560124260957',
      projectId: 'skill-hub-9333f',
      storageBucket: 'skill-hub-9333f.firebasestorage.app',
    );
  }
}
